export default {
  logo: require('../assets/images/logo.png'),
  onBoarding_bg: require('../assets/images/onBoarding_bg.png'),
  onBoarding_1: require('../assets/images/onBoarding_1.png'),
  onBoarding_2: require('../assets/images/onBoarding_2.png'),
  onBoarding_3: require('../assets/images/onBoarding_3.png'),
  onBoarding_4: require('../assets/images/onBoarding_4.png'),
  choose_wide_range: require('../assets/images/choose_wide_range.png'),
  get_your_documentation: require('../assets/images/get_your_documentation.png'),
  choose_wide_range: require('../assets/images/choose_wide_range.png'),
  car_delivery: require('../assets/images/car_delivery.png'),
  cat_1: require('../assets/images/cat_1.png'),
  cat_2: require('../assets/images/cat_2.png'),
  cat_3: require('../assets/images/cat_3.png'),
  cat_4: require('../assets/images/cat_4.png'),
  cat_5: require('../assets/images/cat_5.png'),
  gift: require('../assets/images/gift.png'),
  bell: require('../assets/images/bell.png'),
  flag: require('../assets/images/flag.png'),
  dropdown: require('../assets/images/dropdown.png'),
  banner: require('../assets/images/banner.png'),
  home: require('../assets/images/home.png'),
  explore: require('../assets/images/explore.png'),
  bookings: require('../assets/images/bookings.png'),
  people: require('../assets/images/people.png'),
};
